version: '3.8'

services:
  flaskapp:
    image: srikarmaddy/strawhatpirates:v1
    container_name: flaskapp
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge