version: '3.8'

services:
  flaskapp:
    image: srikarmaddy/strawhatpirates:v1  # Replace with your Flask app's image name
    container_name: flaskapp
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

  corenlp:
    image: nlpbox/corenlp
    container_name: corenlp
    ports:
      - "9000:9000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge